// <auto-generated />
using System;
using Labb4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb4.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookShelfNumber")
                        .HasColumnType("int");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BorrowingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isBorrowed")
                        .HasColumnType("bit");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "Adam Silvera",
                            BookDescription = "Adam Silvera reminds us that there's no life without death and no love without loss in this devastating yet uplifting story about two people whose lives change over the course of one unforgettable day.",
                            BookShelfNumber = 10,
                            BookTitle = "They Both Die at the End",
                            BorrowingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\they-both-die-at-the-endCOVER.jpg",
                            ISBN = "9780062457806",
                            Language = "English",
                            Pages = 416,
                            ReleaseDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = false
                        },
                        new
                        {
                            BookID = 2,
                            Author = "ALLISON SAFT",
                            BookDescription = "A rich and tender YA fantasy love story: Wes and Maggie compete for glory - and each other's hearts - in a magical fox hunt. Perfect for fans of Sorcery of Thorns and Finbar Hawkins.",
                            BookShelfNumber = 12,
                            BookTitle = "Far Wilder Magic",
                            BorrowingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\far-wilder-magicCOVER.jpg",
                            ISBN = "9781510110755",
                            Language = "English",
                            Pages = 384,
                            ReleaseDate = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = false
                        },
                        new
                        {
                            BookID = 3,
                            Author = "Diana Wynne Jones",
                            BookDescription = "This entrancing classic fantasy novel is filled with surprises at every turn. An international bestseller, this much-loved book is the source for the Academy Award nominee for Best Animated Feature.",
                            BookShelfNumber = 11,
                            BookTitle = "Howl's Moving Castle",
                            BorrowingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\howls-moving-castleCOVER.jpg",
                            ISBN = "9780061478789",
                            Language = "English",
                            Pages = 448,
                            ReleaseDate = new DateTime(2008, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = false
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Julian Barnes",
                            BookDescription = "Barnes nya roman är en lika hemlighetsfullt berättad bladvändare som hans kanske mest kända bok Känslan av ett slut.",
                            BookShelfNumber = 14,
                            BookTitle = "Elizabeth Finch",
                            BorrowingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\elizabeth-finch_COVER.jfif",
                            ISBN = "9789177425779",
                            Language = "Swedish",
                            Pages = 220,
                            ReleaseDate = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = false
                        },
                        new
                        {
                            BookID = 5,
                            Author = "Hans-Gunnar Axberger",
                            BookDescription = "När chefsåklagare Krister Petersson vid en presskonferens i juni 2020 meddelade sitt beslut att avsluta utredningen av mordet på Olof Palme, med motiveringen att den misstänkte var avliden, blev det ett kollektivt antiklimax för många svenskar.",
                            BookShelfNumber = 4,
                            BookTitle = "Statsministermordet",
                            BorrowingStartDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\Statsministermordet_COVER.jfif",
                            ISBN = "9789113118994",
                            Language = "Swedish",
                            Pages = 456,
                            ReleaseDate = new DateTime(2022, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = true
                        },
                        new
                        {
                            BookID = 6,
                            Author = "Martin Kleppmann",
                            BookDescription = "Data is at the center of many challenges in system design today. Difficult issues need to be figured out, such as scalability, consistency, reliability, efficiency, and maintainability. In addition, we have an overwhelming variety of tools, including NoSQL datastores, stream or batch processors, and message brokers.",
                            BookShelfNumber = 1,
                            BookTitle = "Designing Data-Intensive Applications",
                            BorrowingStartDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\designing-data-intensive-applications_COVER.jfif",
                            ISBN = "9781449373320",
                            Language = "English",
                            Pages = 562,
                            ReleaseDate = new DateTime(2017, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = true
                        },
                        new
                        {
                            BookID = 7,
                            Author = "Robert C Martin",
                            BookDescription = "Even bad code can function. But if code isnt clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesnt have to be that way.",
                            BookShelfNumber = 1,
                            BookTitle = "Clean Code: A Handbook Of Agile Software Craftsmanship",
                            BorrowingStartDate = new DateTime(2022, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\clean-code-a-handbook-of-agile-software-craftsmanship_COVER.jfif",
                            ISBN = "9780132350884",
                            Language = "English",
                            Pages = 464,
                            ReleaseDate = new DateTime(2008, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = true
                        },
                        new
                        {
                            BookID = 8,
                            Author = "Mons Kallentoft",
                            BookDescription = "Om du inte lagt upp det på instagram, har det hänt? Om du inte finns på instagram, finns du? Om du finns på instagram, kommer du att dö? En känd influencer hittas dumpad i en container, naken och med Gucciträningsoverallen och Rolexklockan slängda över liket. ",
                            BookShelfNumber = 4,
                            BookTitle = "Grissly",
                            BorrowingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\grissly_COVER.jfif",
                            ISBN = "9789137156149",
                            Language = "Swedish",
                            Pages = 350,
                            ReleaseDate = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = false
                        },
                        new
                        {
                            BookID = 9,
                            Author = "Eva Bodfäldt",
                            BookDescription = "Utan glädje kommer vi ingenstans i samvaron med våra hundar. Utan kunskap om vad vi själva behöver göra kommer vi inte heller någonstans. Min syn på hundträning bygger på att vi utvecklar relationen med hundenutan att använda kommandon.",
                            BookShelfNumber = 8,
                            BookTitle = "Kontaktkontraktet : en bok om människans samspel med hunden - från valp till vuxen",
                            BorrowingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\kontaktkontraktet-en-bok-om-manniskans-samspel-med-hunden-fran-valp-till-vuxen_COVER.jfif",
                            ISBN = "9789197357876",
                            Language = "Swedish",
                            Pages = 207,
                            ReleaseDate = new DateTime(2016, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = false
                        },
                        new
                        {
                            BookID = 10,
                            Author = " C S Lewis",
                            BookDescription = "Beloved by generations for more than 50 years, this classic children's series is now available in an adult edition.",
                            BookShelfNumber = 2,
                            BookTitle = "Complete Chronicles Of Narnia",
                            BorrowingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\complete-chronicles-of-narnia_Cover.jfif",
                            ISBN = "9780066238500",
                            Language = "English",
                            Pages = 768,
                            ReleaseDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = false
                        },
                        new
                        {
                            BookID = 11,
                            Author = "Thomas Piketty",
                            BookDescription = "The world's leading economist of inequality presents a short but sweeping and surprisingly optimistic history of human progress toward equality despite crises, disasters, and backsliding.",
                            BookShelfNumber = 16,
                            BookTitle = "A Brief History of Equality",
                            BorrowingStartDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\a-brief-history-of-equality_COVER.jfif",
                            ISBN = "9780674273559",
                            Language = "English",
                            Pages = 288,
                            ReleaseDate = new DateTime(2022, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = true
                        },
                        new
                        {
                            BookID = 12,
                            Author = "J R R Tolkien",
                            BookDescription = "Boxed gift set of Tolkien's classic masterpieces, fully illustrated throughout in watercolour by the acclaimed and award-winning artist, Alan Lee, Conceptual Designer on Peter Jackson's THE HOBBIT films. ",
                            BookShelfNumber = 2,
                            BookTitle = "The Hobbit &; The Lord of the Rings Boxed Set",
                            BorrowingStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverImageUrl = "\\Images\\the-hobbit-the-lord-of-the-rings-boxed-set_COVER.jfif",
                            ISBN = "9780008376109",
                            Language = "English",
                            Pages = 1601,
                            ReleaseDate = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isBorrowed = false
                        });
                });

            modelBuilder.Entity("Labb4.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            CustomerEmail = "Klara.Berg@Email.com",
                            CustomerName = "Klara Berg"
                        },
                        new
                        {
                            CustomerID = 2,
                            CustomerEmail = "Nalle.Puh@Honung.com",
                            CustomerName = "Nalle Puh"
                        },
                        new
                        {
                            CustomerID = 3,
                            CustomerEmail = "Kiki.Witch@Delivery.com",
                            CustomerName = "Kiki Witch"
                        });
                });

            modelBuilder.Entity("Labb4.Models.Customer_Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 5,
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 6,
                            CustomerId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 7,
                            CustomerId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 11,
                            CustomerId = 3
                        });
                });

            modelBuilder.Entity("Labb4.Models.Customer_Book", b =>
                {
                    b.HasOne("Labb4.Models.Book", "Book")
                        .WithMany("joinCustomeBook")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb4.Models.Customer", "Customer")
                        .WithMany("joinCustomeBook")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
